export const ATAQUES_70 = [
  {
    name: "Ataque Especial 1",
    type: "atk",
    descripcion: "Habilidad de tipo atk con interacción dinámica.",
    mana: 16,
    prioridad: 4,
    item: null,
    set: null,
    efecto: "Daño directo, estado o buff segun tipo atk",
    reaccionA: null,
    counter: null,
    recounter: null,
    dobleefecto: null,
    condicion: null,
  },
  {
    name: "Ataque Especial 2",
    type: "hatk",
    descripcion: "Habilidad de tipo hatk con interacción dinámica.",
    mana: 7,
    prioridad: 3,
    item: null,
    set: null,
    efecto: "Daño directo, estado o buff segun tipo hatk",
    reaccionA: "Condición específica o estado",
    counter: "Ataque Especial 1",
    recounter: null,
    dobleefecto: null,
    condicion: null,
  },
  {
    name: "Ataque Especial 3",
    type: "hatk",
    descripcion: "Habilidad de tipo hatk con interacción dinámica.",
    mana: 20,
    prioridad: 4,
    item: null,
    set: null,
    efecto: "Daño directo, estado o buff segun tipo hatk",
    reaccionA: "Condición específica o estado",
    counter: "Ataque Especial 2",
    recounter: "Ataque Especial 1",
    dobleefecto: null,
    condicion: null,
  },
  {
    name: "Ataque Especial 4",
    type: "def",
    descripcion: "Habilidad de tipo def con interacción dinámica.",
    mana: 18,
    prioridad: 5,
    item: null,
    set: null,
    efecto: "Daño directo, estado o buff segun tipo def",
    reaccionA: "Condición específica o estado",
    counter: "Ataque Especial 3",
    recounter: "Ataque Especial 2",
    dobleefecto: null,
    condicion: null,
  },
  {
    name: "Ataque Especial 5",
    type: "item_skill",
    descripcion: "Habilidad de tipo item_skill con interacción dinámica.",
    mana: 20,
    prioridad: 5,
    item: null,
    set: null,
    efecto: "Daño directo, estado o buff segun tipo item_skill",
    reaccionA: null,
    counter: null,
    recounter: null,
    dobleefecto: "Efecto extra si el enemigo está envenenado",
    condicion: null,
  },
  {
    name: "Ataque Especial 6",
    type: "hatk",
    descripcion: "Habilidad de tipo hatk con interacción dinámica.",
    mana: 9,
    prioridad: 3,
    item: null,
    set: null,
    efecto: "Daño directo, estado o buff segun tipo hatk",
    reaccionA: "Condición específica o estado",
    counter: "Ataque Especial 5",
    recounter: "Ataque Especial 4",
    dobleefecto: null,
    condicion: null,
  },
  {
    name: "Ataque Especial 7",
    type: "def",
    descripcion: "Habilidad de tipo def con interacción dinámica.",
    mana: 14,
    prioridad: 5,
    item: null,
    set: null,
    efecto: "Daño directo, estado o buff segun tipo def",
    reaccionA: "Condición específica o estado",
    counter: "Ataque Especial 6",
    recounter: "Ataque Especial 5",
    dobleefecto: null,
    condicion: null,
  },
  {
    name: "Ataque Especial 8",
    type: "set_skill",
    descripcion: "Habilidad de tipo set_skill con interacción dinámica.",
    mana: 0,
    prioridad: 6,
    item: null,
    set: "Set de Guerra 8",
    efecto: "Daño directo, estado o buff segun tipo set_skill",
    reaccionA: null,
    counter: null,
    recounter: null,
    dobleefecto: null,
    condicion: null,
  },
  {
    name: "Ataque Especial 9",
    type: "atk",
    descripcion: "Habilidad de tipo atk con interacción dinámica.",
    mana: 5,
    prioridad: 4,
    item: null,
    set: null,
    efecto: "Daño directo, estado o buff segun tipo atk",
    reaccionA: null,
    counter: null,
    recounter: null,
    dobleefecto: null,
    condicion: null,
  },
  {
    name: "Ataque Especial 10",
    type: "set_skill",
    descripcion: "Habilidad de tipo set_skill con interacción dinámica.",
    mana: 0,
    prioridad: 6,
    item: null,
    set: "Set de Guerra 0",
    efecto: "Daño directo, estado o buff segun tipo set_skill",
    reaccionA: null,
    counter: null,
    recounter: null,
    dobleefecto: null,
    condicion: null,
  },
  {
    name: "Ataque Especial 11",
    type: "hatk",
    descripcion: "Habilidad de tipo hatk con interacción dinámica.",
    mana: 10,
    prioridad: 4,
    item: null,
    set: null,
    efecto: "Daño directo, estado o buff segun tipo hatk",
    reaccionA: "Condición específica o estado",
    counter: "Ataque Especial 10",
    recounter: "Ataque Especial 9",
    dobleefecto: null,
    condicion: null,
  },
  {
    name: "Ataque Especial 12",
    type: "def",
    descripcion: "Habilidad de tipo def con interacción dinámica.",
    mana: 10,
    prioridad: 2,
    item: null,
    set: null,
    efecto: "Daño directo, estado o buff segun tipo def",
    reaccionA: "Condición específica o estado",
    counter: "Ataque Especial 11",
    recounter: "Ataque Especial 10",
    dobleefecto: null,
    condicion: null,
  },
  {
    name: "Ataque Especial 13",
    type: "set_skill",
    descripcion: "Habilidad de tipo set_skill con interacción dinámica.",
    mana: 0,
    prioridad: 6,
    item: null,
    set: "Set de Guerra 3",
    efecto: "Daño directo, estado o buff segun tipo set_skill",
    reaccionA: null,
    counter: null,
    recounter: null,
    dobleefecto: null,
    condicion: null,
  },
  {
    name: "Ataque Especial 14",
    type: "def",
    descripcion: "Habilidad de tipo def con interacción dinámica.",
    mana: 19,
    prioridad: 5,
    item: null,
    set: null,
    efecto: "Daño directo, estado o buff segun tipo def",
    reaccionA: "Condición específica o estado",
    counter: "Ataque Especial 13",
    recounter: "Ataque Especial 12",
    dobleefecto: null,
    condicion: null,
  },
  {
    name: "Ataque Especial 15",
    type: "hatk",
    descripcion: "Habilidad de tipo hatk con interacción dinámica.",
    mana: 18,
    prioridad: 2,
    item: null,
    set: null,
    efecto: "Daño directo, estado o buff segun tipo hatk",
    reaccionA: "Condición específica o estado",
    counter: "Ataque Especial 14",
    recounter: "Ataque Especial 13",
    dobleefecto: "Efecto extra si el enemigo está envenenado",
    condicion: null,
  },
  {
    name: "Ataque Especial 16",
    type: "atk",
    descripcion: "Habilidad de tipo atk con interacción dinámica.",
    mana: 12,
    prioridad: 4,
    item: null,
    set: null,
    efecto: "Daño directo, estado o buff segun tipo atk",
    reaccionA: null,
    counter: null,
    recounter: null,
    dobleefecto: null,
    condicion: null,
  },
  {
    name: "Ataque Especial 17",
    type: "atk",
    descripcion: "Habilidad de tipo atk con interacción dinámica.",
    mana: 13,
    prioridad: 4,
    item: null,
    set: null,
    efecto: "Daño directo, estado o buff segun tipo atk",
    reaccionA: null,
    counter: null,
    recounter: null,
    dobleefecto: null,
    condicion: null,
  },
  {
    name: "Ataque Especial 18",
    type: "set_skill",
    descripcion: "Habilidad de tipo set_skill con interacción dinámica.",
    mana: 0,
    prioridad: 6,
    item: null,
    set: "Set de Guerra 8",
    efecto: "Daño directo, estado o buff segun tipo set_skill",
    reaccionA: null,
    counter: null,
    recounter: null,
    dobleefecto: null,
    condicion: null,
  },
  {
    name: "Ataque Especial 19",
    type: "atk",
    descripcion: "Habilidad de tipo atk con interacción dinámica.",
    mana: 5,
    prioridad: 2,
    item: null,
    set: null,
    efecto: "Daño directo, estado o buff segun tipo atk",
    reaccionA: null,
    counter: null,
    recounter: null,
    dobleefecto: null,
    condicion: null,
  },
  {
    name: "Ataque Especial 20",
    type: "hatk",
    descripcion: "Habilidad de tipo hatk con interacción dinámica.",
    mana: 14,
    prioridad: 5,
    item: null,
    set: null,
    efecto: "Daño directo, estado o buff segun tipo hatk",
    reaccionA: "Condición específica o estado",
    counter: "Ataque Especial 19",
    recounter: "Ataque Especial 18",
    dobleefecto: "Efecto extra si el enemigo está envenenado",
    condicion: "Enemigo con escudo activo",
  },
  {
    name: "Ataque Especial 21",
    type: "item_skill",
    descripcion: "Habilidad de tipo item_skill con interacción dinámica.",
    mana: 12,
    prioridad: 4,
    item: "Anillo de Absorción",
    set: null,
    efecto: "Daño directo, estado o buff segun tipo item_skill",
    reaccionA: null,
    counter: null,
    recounter: null,
    dobleefecto: null,
    condicion: null,
  },
  {
    name: "Ataque Especial 22",
    type: "atk",
    descripcion: "Habilidad de tipo atk con interacción dinámica.",
    mana: 17,
    prioridad: 3,
    item: null,
    set: null,
    efecto: "Daño directo, estado o buff segun tipo atk",
    reaccionA: null,
    counter: null,
    recounter: null,
    dobleefecto: null,
    condicion: null,
  },
  {
    name: "Ataque Especial 23",
    type: "item_skill",
    descripcion: "Habilidad de tipo item_skill con interacción dinámica.",
    mana: 6,
    prioridad: 5,
    item: null,
    set: null,
    efecto: "Daño directo, estado o buff segun tipo item_skill",
    reaccionA: null,
    counter: null,
    recounter: null,
    dobleefecto: null,
    condicion: null,
  },
  {
    name: "Ataque Especial 24",
    type: "item_skill",
    descripcion: "Habilidad de tipo item_skill con interacción dinámica.",
    mana: 14,
    prioridad: 2,
    item: null,
    set: null,
    efecto: "Daño directo, estado o buff segun tipo item_skill",
    reaccionA: null,
    counter: null,
    recounter: null,
    dobleefecto: null,
    condicion: "Enemigo con escudo activo",
  },
  {
    name: "Ataque Especial 25",
    type: "hatk",
    descripcion: "Habilidad de tipo hatk con interacción dinámica.",
    mana: 12,
    prioridad: 3,
    item: null,
    set: null,
    efecto: "Daño directo, estado o buff segun tipo hatk",
    reaccionA: "Condición específica o estado",
    counter: "Ataque Especial 24",
    recounter: "Ataque Especial 23",
    dobleefecto: "Efecto extra si el enemigo está envenenado",
    condicion: null,
  },
  {
    name: "Ataque Especial 26",
    type: "def",
    descripcion: "Habilidad de tipo def con interacción dinámica.",
    mana: 6,
    prioridad: 2,
    item: null,
    set: null,
    efecto: "Daño directo, estado o buff segun tipo def",
    reaccionA: "Condición específica o estado",
    counter: "Ataque Especial 25",
    recounter: "Ataque Especial 24",
    dobleefecto: null,
    condicion: null,
  },
  {
    name: "Ataque Especial 27",
    type: "set_skill",
    descripcion: "Habilidad de tipo set_skill con interacción dinámica.",
    mana: 0,
    prioridad: 6,
    item: null,
    set: "Set de Guerra 7",
    efecto: "Daño directo, estado o buff segun tipo set_skill",
    reaccionA: null,
    counter: null,
    recounter: null,
    dobleefecto: null,
    condicion: null,
  },
  {
    name: "Ataque Especial 28",
    type: "def",
    descripcion: "Habilidad de tipo def con interacción dinámica.",
    mana: 12,
    prioridad: 4,
    item: null,
    set: null,
    efecto: "Daño directo, estado o buff segun tipo def",
    reaccionA: "Condición específica o estado",
    counter: "Ataque Especial 27",
    recounter: "Ataque Especial 26",
    dobleefecto: null,
    condicion: null,
  },
  {
    name: "Ataque Especial 29",
    type: "atk",
    descripcion: "Habilidad de tipo atk con interacción dinámica.",
    mana: 14,
    prioridad: 3,
    item: null,
    set: null,
    efecto: "Daño directo, estado o buff segun tipo atk",
    reaccionA: null,
    counter: null,
    recounter: null,
    dobleefecto: null,
    condicion: null,
  },
  {
    name: "Ataque Especial 30",
    type: "set_skill",
    descripcion: "Habilidad de tipo set_skill con interacción dinámica.",
    mana: 0,
    prioridad: 6,
    item: null,
    set: "Set de Guerra 0",
    efecto: "Daño directo, estado o buff segun tipo set_skill",
    reaccionA: null,
    counter: null,
    recounter: null,
    dobleefecto: null,
    condicion: null,
  },
  {
    name: "Ataque Especial 31",
    type: "item_skill",
    descripcion: "Habilidad de tipo item_skill con interacción dinámica.",
    mana: 8,
    prioridad: 2,
    item: "Espada de Fuego",
    set: null,
    efecto: "Daño directo, estado o buff segun tipo item_skill",
    reaccionA: null,
    counter: null,
    recounter: null,
    dobleefecto: null,
    condicion: null,
  },
  {
    name: "Ataque Especial 32",
    type: "def",
    descripcion: "Habilidad de tipo def con interacción dinámica.",
    mana: 10,
    prioridad: 3,
    item: null,
    set: null,
    efecto: "Daño directo, estado o buff segun tipo def",
    reaccionA: "Condición específica o estado",
    counter: "Ataque Especial 31",
    recounter: "Ataque Especial 30",
    dobleefecto: null,
    condicion: null,
  },
  {
    name: "Ataque Especial 33",
    type: "atk",
    descripcion: "Habilidad de tipo atk con interacción dinámica.",
    mana: 11,
    prioridad: 5,
    item: null,
    set: null,
    efecto: "Daño directo, estado o buff segun tipo atk",
    reaccionA: null,
    counter: null,
    recounter: null,
    dobleefecto: null,
    condicion: null,
  },
  {
    name: "Ataque Especial 34",
    type: "atk",
    descripcion: "Habilidad de tipo atk con interacción dinámica.",
    mana: 9,
    prioridad: 5,
    item: null,
    set: null,
    efecto: "Daño directo, estado o buff segun tipo atk",
    reaccionA: null,
    counter: null,
    recounter: null,
    dobleefecto: null,
    condicion: null,
  },
  {
    name: "Ataque Especial 35",
    type: "hatk",
    descripcion: "Habilidad de tipo hatk con interacción dinámica.",
    mana: 11,
    prioridad: 2,
    item: null,
    set: null,
    efecto: "Daño directo, estado o buff segun tipo hatk",
    reaccionA: "Condición específica o estado",
    counter: "Ataque Especial 34",
    recounter: "Ataque Especial 33",
    dobleefecto: "Efecto extra si el enemigo está envenenado",
    condicion: null,
  },
  {
    name: "Ataque Especial 36",
    type: "atk",
    descripcion: "Habilidad de tipo atk con interacción dinámica.",
    mana: 10,
    prioridad: 4,
    item: null,
    set: null,
    efecto: "Daño directo, estado o buff segun tipo atk",
    reaccionA: null,
    counter: null,
    recounter: null,
    dobleefecto: null,
    condicion: null,
  },
  {
    name: "Ataque Especial 37",
    type: "set_skill",
    descripcion: "Habilidad de tipo set_skill con interacción dinámica.",
    mana: 0,
    prioridad: 6,
    item: null,
    set: "Set de Guerra 7",
    efecto: "Daño directo, estado o buff segun tipo set_skill",
    reaccionA: null,
    counter: null,
    recounter: null,
    dobleefecto: null,
    condicion: null,
  },
  {
    name: "Ataque Especial 38",
    type: "def",
    descripcion: "Habilidad de tipo def con interacción dinámica.",
    mana: 10,
    prioridad: 2,
    item: null,
    set: null,
    efecto: "Daño directo, estado o buff segun tipo def",
    reaccionA: "Condición específica o estado",
    counter: "Ataque Especial 37",
    recounter: "Ataque Especial 36",
    dobleefecto: null,
    condicion: null,
  },
  {
    name: "Ataque Especial 39",
    type: "def",
    descripcion: "Habilidad de tipo def con interacción dinámica.",
    mana: 17,
    prioridad: 5,
    item: null,
    set: null,
    efecto: "Daño directo, estado o buff segun tipo def",
    reaccionA: "Condición específica o estado",
    counter: "Ataque Especial 38",
    recounter: "Ataque Especial 37",
    dobleefecto: null,
    condicion: null,
  },
  {
    name: "Ataque Especial 40",
    type: "def",
    descripcion: "Habilidad de tipo def con interacción dinámica.",
    mana: 5,
    prioridad: 2,
    item: null,
    set: null,
    efecto: "Daño directo, estado o buff segun tipo def",
    reaccionA: "Condición específica o estado",
    counter: "Ataque Especial 39",
    recounter: "Ataque Especial 38",
    dobleefecto: null,
    condicion: null,
  },
  {
    name: "Ataque Especial 41",
    type: "set_skill",
    descripcion: "Habilidad de tipo set_skill con interacción dinámica.",
    mana: 0,
    prioridad: 6,
    item: null,
    set: "Set de Guerra 1",
    efecto: "Daño directo, estado o buff segun tipo set_skill",
    reaccionA: null,
    counter: null,
    recounter: null,
    dobleefecto: null,
    condicion: null,
  },
  {
    name: "Ataque Especial 42",
    type: "item_skill",
    descripcion: "Habilidad de tipo item_skill con interacción dinámica.",
    mana: 5,
    prioridad: 4,
    item: "Anillo de Absorción",
    set: null,
    efecto: "Daño directo, estado o buff segun tipo item_skill",
    reaccionA: null,
    counter: null,
    recounter: null,
    dobleefecto: null,
    condicion: null,
  },
  {
    name: "Ataque Especial 43",
    type: "set_skill",
    descripcion: "Habilidad de tipo set_skill con interacción dinámica.",
    mana: 0,
    prioridad: 6,
    item: null,
    set: "Set de Guerra 3",
    efecto: "Daño directo, estado o buff segun tipo set_skill",
    reaccionA: null,
    counter: null,
    recounter: null,
    dobleefecto: null,
    condicion: null,
  },
  {
    name: "Ataque Especial 44",
    type: "hatk",
    descripcion: "Habilidad de tipo hatk con interacción dinámica.",
    mana: 17,
    prioridad: 4,
    item: null,
    set: null,
    efecto: "Daño directo, estado o buff segun tipo hatk",
    reaccionA: "Condición específica o estado",
    counter: "Ataque Especial 43",
    recounter: "Ataque Especial 42",
    dobleefecto: null,
    condicion: "Enemigo con escudo activo",
  },
  {
    name: "Ataque Especial 45",
    type: "set_skill",
    descripcion: "Habilidad de tipo set_skill con interacción dinámica.",
    mana: 0,
    prioridad: 6,
    item: null,
    set: "Set de Guerra 5",
    efecto: "Daño directo, estado o buff segun tipo set_skill",
    reaccionA: null,
    counter: null,
    recounter: null,
    dobleefecto: null,
    condicion: null,
  },
  {
    name: "Ataque Especial 46",
    type: "set_skill",
    descripcion: "Habilidad de tipo set_skill con interacción dinámica.",
    mana: 0,
    prioridad: 6,
    item: null,
    set: "Set de Guerra 6",
    efecto: "Daño directo, estado o buff segun tipo set_skill",
    reaccionA: null,
    counter: null,
    recounter: null,
    dobleefecto: null,
    condicion: null,
  },
  {
    name: "Ataque Especial 47",
    type: "def",
    descripcion: "Habilidad de tipo def con interacción dinámica.",
    mana: 15,
    prioridad: 3,
    item: null,
    set: null,
    efecto: "Daño directo, estado o buff segun tipo def",
    reaccionA: "Condición específica o estado",
    counter: "Ataque Especial 46",
    recounter: "Ataque Especial 45",
    dobleefecto: null,
    condicion: null,
  },
  {
    name: "Ataque Especial 48",
    type: "set_skill",
    descripcion: "Habilidad de tipo set_skill con interacción dinámica.",
    mana: 0,
    prioridad: 6,
    item: null,
    set: "Set de Guerra 8",
    efecto: "Daño directo, estado o buff segun tipo set_skill",
    reaccionA: null,
    counter: null,
    recounter: null,
    dobleefecto: null,
    condicion: null,
  },
  {
    name: "Ataque Especial 49",
    type: "atk",
    descripcion: "Habilidad de tipo atk con interacción dinámica.",
    mana: 6,
    prioridad: 4,
    item: null,
    set: null,
    efecto: "Daño directo, estado o buff segun tipo atk",
    reaccionA: null,
    counter: null,
    recounter: null,
    dobleefecto: null,
    condicion: null,
  },
  {
    name: "Ataque Especial 50",
    type: "set_skill",
    descripcion: "Habilidad de tipo set_skill con interacción dinámica.",
    mana: 0,
    prioridad: 6,
    item: null,
    set: "Set de Guerra 0",
    efecto: "Daño directo, estado o buff segun tipo set_skill",
    reaccionA: null,
    counter: null,
    recounter: null,
    dobleefecto: null,
    condicion: null,
  },
  {
    name: "Ataque Especial 51",
    type: "def",
    descripcion: "Habilidad de tipo def con interacción dinámica.",
    mana: 17,
    prioridad: 3,
    item: null,
    set: null,
    efecto: "Daño directo, estado o buff segun tipo def",
    reaccionA: "Condición específica o estado",
    counter: "Ataque Especial 50",
    recounter: "Ataque Especial 49",
    dobleefecto: null,
    condicion: null,
  },
  {
    name: "Ataque Especial 52",
    type: "hatk",
    descripcion: "Habilidad de tipo hatk con interacción dinámica.",
    mana: 17,
    prioridad: 4,
    item: null,
    set: null,
    efecto: "Daño directo, estado o buff segun tipo hatk",
    reaccionA: "Condición específica o estado",
    counter: "Ataque Especial 51",
    recounter: "Ataque Especial 50",
    dobleefecto: null,
    condicion: "Enemigo con escudo activo",
  },
  {
    name: "Ataque Especial 53",
    type: "item_skill",
    descripcion: "Habilidad de tipo item_skill con interacción dinámica.",
    mana: 9,
    prioridad: 4,
    item: "Manto de Sombras",
    set: null,
    efecto: "Daño directo, estado o buff segun tipo item_skill",
    reaccionA: null,
    counter: null,
    recounter: null,
    dobleefecto: null,
    condicion: null,
  },
  {
    name: "Ataque Especial 54",
    type: "set_skill",
    descripcion: "Habilidad de tipo set_skill con interacción dinámica.",
    mana: 0,
    prioridad: 6,
    item: null,
    set: "Set de Guerra 4",
    efecto: "Daño directo, estado o buff segun tipo set_skill",
    reaccionA: null,
    counter: null,
    recounter: null,
    dobleefecto: null,
    condicion: null,
  },
  {
    name: "Ataque Especial 55",
    type: "set_skill",
    descripcion: "Habilidad de tipo set_skill con interacción dinámica.",
    mana: 0,
    prioridad: 6,
    item: null,
    set: "Set de Guerra 5",
    efecto: "Daño directo, estado o buff segun tipo set_skill",
    reaccionA: null,
    counter: null,
    recounter: null,
    dobleefecto: null,
    condicion: null,
  },
  {
    name: "Ataque Especial 56",
    type: "atk",
    descripcion: "Habilidad de tipo atk con interacción dinámica.",
    mana: 10,
    prioridad: 3,
    item: null,
    set: null,
    efecto: "Daño directo, estado o buff segun tipo atk",
    reaccionA: null,
    counter: null,
    recounter: null,
    dobleefecto: null,
    condicion: null,
  },
  {
    name: "Ataque Especial 57",
    type: "def",
    descripcion: "Habilidad de tipo def con interacción dinámica.",
    mana: 14,
    prioridad: 5,
    item: null,
    set: null,
    efecto: "Daño directo, estado o buff segun tipo def",
    reaccionA: "Condición específica o estado",
    counter: "Ataque Especial 56",
    recounter: "Ataque Especial 55",
    dobleefecto: null,
    condicion: null,
  },
  {
    name: "Ataque Especial 58",
    type: "def",
    descripcion: "Habilidad de tipo def con interacción dinámica.",
    mana: 12,
    prioridad: 3,
    item: null,
    set: null,
    efecto: "Daño directo, estado o buff segun tipo def",
    reaccionA: "Condición específica o estado",
    counter: "Ataque Especial 57",
    recounter: "Ataque Especial 56",
    dobleefecto: null,
    condicion: null,
  },
  {
    name: "Ataque Especial 59",
    type: "item_skill",
    descripcion: "Habilidad de tipo item_skill con interacción dinámica.",
    mana: 8,
    prioridad: 5,
    item: "Espada de Fuego",
    set: null,
    efecto: "Daño directo, estado o buff segun tipo item_skill",
    reaccionA: null,
    counter: null,
    recounter: null,
    dobleefecto: null,
    condicion: null,
  },
  {
    name: "Ataque Especial 60",
    type: "hatk",
    descripcion: "Habilidad de tipo hatk con interacción dinámica.",
    mana: 14,
    prioridad: 5,
    item: null,
    set: null,
    efecto: "Daño directo, estado o buff segun tipo hatk",
    reaccionA: "Condición específica o estado",
    counter: "Ataque Especial 59",
    recounter: "Ataque Especial 58",
    dobleefecto: "Efecto extra si el enemigo está envenenado",
    condicion: "Enemigo con escudo activo",
  },
  {
    name: "Ataque Especial 61",
    type: "atk",
    descripcion: "Habilidad de tipo atk con interacción dinámica.",
    mana: 12,
    prioridad: 4,
    item: null,
    set: null,
    efecto: "Daño directo, estado o buff segun tipo atk",
    reaccionA: null,
    counter: null,
    recounter: null,
    dobleefecto: null,
    condicion: null,
  },
  {
    name: "Ataque Especial 62",
    type: "def",
    descripcion: "Habilidad de tipo def con interacción dinámica.",
    mana: 5,
    prioridad: 4,
    item: null,
    set: null,
    efecto: "Daño directo, estado o buff segun tipo def",
    reaccionA: "Condición específica o estado",
    counter: "Ataque Especial 61",
    recounter: "Ataque Especial 60",
    dobleefecto: null,
    condicion: null,
  },
  {
    name: "Ataque Especial 63",
    type: "set_skill",
    descripcion: "Habilidad de tipo set_skill con interacción dinámica.",
    mana: 0,
    prioridad: 6,
    item: null,
    set: "Set de Guerra 3",
    efecto: "Daño directo, estado o buff segun tipo set_skill",
    reaccionA: null,
    counter: null,
    recounter: null,
    dobleefecto: null,
    condicion: null,
  },
  {
    name: "Ataque Especial 64",
    type: "def",
    descripcion: "Habilidad de tipo def con interacción dinámica.",
    mana: 6,
    prioridad: 5,
    item: null,
    set: null,
    efecto: "Daño directo, estado o buff segun tipo def",
    reaccionA: "Condición específica o estado",
    counter: "Ataque Especial 63",
    recounter: "Ataque Especial 62",
    dobleefecto: null,
    condicion: null,
  },
  {
    name: "Ataque Especial 65",
    type: "def",
    descripcion: "Habilidad de tipo def con interacción dinámica.",
    mana: 17,
    prioridad: 3,
    item: null,
    set: null,
    efecto: "Daño directo, estado o buff segun tipo def",
    reaccionA: "Condición específica o estado",
    counter: "Ataque Especial 64",
    recounter: "Ataque Especial 63",
    dobleefecto: null,
    condicion: null,
  },
  {
    name: "Ataque Especial 66",
    type: "def",
    descripcion: "Habilidad de tipo def con interacción dinámica.",
    mana: 9,
    prioridad: 4,
    item: null,
    set: null,
    efecto: "Daño directo, estado o buff segun tipo def",
    reaccionA: "Condición específica o estado",
    counter: "Ataque Especial 65",
    recounter: "Ataque Especial 64",
    dobleefecto: null,
    condicion: null,
  },
  {
    name: "Ataque Especial 67",
    type: "set_skill",
    descripcion: "Habilidad de tipo set_skill con interacción dinámica.",
    mana: 0,
    prioridad: 6,
    item: null,
    set: "Set de Guerra 7",
    efecto: "Daño directo, estado o buff segun tipo set_skill",
    reaccionA: null,
    counter: null,
    recounter: null,
    dobleefecto: null,
    condicion: null,
  },
  {
    name: "Ataque Especial 68",
    type: "hatk",
    descripcion: "Habilidad de tipo hatk con interacción dinámica.",
    mana: 10,
    prioridad: 3,
    item: null,
    set: null,
    efecto: "Daño directo, estado o buff segun tipo hatk",
    reaccionA: "Condición específica o estado",
    counter: "Ataque Especial 67",
    recounter: "Ataque Especial 66",
    dobleefecto: null,
    condicion: "Enemigo con escudo activo",
  },
  {
    name: "Ataque Especial 69",
    type: "item_skill",
    descripcion: "Habilidad de tipo item_skill con interacción dinámica.",
    mana: 17,
    prioridad: 2,
    item: "Espada de Fuego",
    set: null,
    efecto: "Daño directo, estado o buff segun tipo item_skill",
    reaccionA: null,
    counter: null,
    recounter: null,
    dobleefecto: null,
    condicion: null,
  },
  {
    name: "Ataque Especial 70",
    type: "def",
    descripcion: "Habilidad de tipo def con interacción dinámica.",
    mana: 13,
    prioridad: 4,
    item: null,
    set: null,
    efecto: "Daño directo, estado o buff segun tipo def",
    reaccionA: "Condición específica o estado",
    counter: "Ataque Especial 69",
    recounter: "Ataque Especial 68",
    dobleefecto: null,
    condicion: null,
  },
];
